services:
  app:
    build: .
    env_file:
      - path: .env
        required: false
    ports:
     - "9336:9336"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: src
          action: rebuild
        - path: Cargo.lock
          action: rebuild
    healthcheck:
      test: httpie --check-status -q GET :9336/healthz || exit 1
      timeout: 2s
      interval: 30s
      start_period: 5s
      start_interval: 1s

  db:
    image: postgres:16.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigtrip
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username user -d bigtrip || exit 1
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  pg_data:
