services:
  app:
    build: .
    env_file:
      - path: .env
        required: false
    ports:
     - "9336:9336"
    develop:
      watch:
        - path: src
          action: rebuild
    healthcheck:
      test: curl localhost:9336/healthz || exit 1
      timeout: 2s
      interval: 3s

  db:
    image: postgres:16.5-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bigtrip
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username user -d bigtrip || exit 1
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  pg_data:
