name: Build app images
run-name: Build version ${{ github.ref_name }}

on:
  push:
    tags:
      - "*"

env:
  S3_BUCKET: big-trip-build-cache

jobs:
  build-backend:
    name: Build backend service
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: Klavionik/gh-actions/build-image@main
        name: Build
        with:
          cache-bucket: ${{ env.S3_BUCKET }}
          cache-access-key: ${{ secrets.S3_ACCESS_KEY }}
          cache-secret-key: ${{ secrets.S3_SECRET_KEY }}
